/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AI聊天请求参数
 * @export
 * @interface AiChatRequest
 */
export interface AiChatRequest {
    /**
     * 用户消息内容
     * @type {string}
     * @memberof AiChatRequest
     */
    message: string;
    /**
     * 对话ID，用于关联上下文，可为空
     * @type {string}
     * @memberof AiChatRequest
     */
    conversationId?: string;
    /**
     * 用户标识
     * @type {string}
     * @memberof AiChatRequest
     */
    user?: string;
}

/**
 * Check if a given object implements the AiChatRequest interface.
 */
export function instanceOfAiChatRequest(value: object): value is AiChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiChatRequestFromJSON(json: any): AiChatRequest {
    return AiChatRequestFromJSONTyped(json, false);
}

export function AiChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function AiChatRequestToJSON(json: any): AiChatRequest {
    return AiChatRequestToJSONTyped(json, false);
}

export function AiChatRequestToJSONTyped(value?: AiChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'conversation_id': value['conversationId'],
        'user': value['user'],
    };
}

