/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 公告响应
 * @export
 * @interface AnnouncementResponse
 */
export interface AnnouncementResponse {
    /**
     * 公告ID
     * @type {number}
     * @memberof AnnouncementResponse
     */
    id?: number;
    /**
     * 公告标题
     * @type {string}
     * @memberof AnnouncementResponse
     */
    title?: string;
    /**
     * 生效时间
     * @type {Date}
     * @memberof AnnouncementResponse
     */
    effectiveTime?: Date;
    /**
     * 过期时间
     * @type {Date}
     * @memberof AnnouncementResponse
     */
    expirationTime?: Date;
    /**
     * 创建时间
     * @type {Date}
     * @memberof AnnouncementResponse
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof AnnouncementResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AnnouncementResponse interface.
 */
export function instanceOfAnnouncementResponse(value: object): value is AnnouncementResponse {
    return true;
}

export function AnnouncementResponseFromJSON(json: any): AnnouncementResponse {
    return AnnouncementResponseFromJSONTyped(json, false);
}

export function AnnouncementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'effectiveTime': json['effectiveTime'] == null ? undefined : (new Date(json['effectiveTime'])),
        'expirationTime': json['expirationTime'] == null ? undefined : (new Date(json['expirationTime'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AnnouncementResponseToJSON(json: any): AnnouncementResponse {
    return AnnouncementResponseToJSONTyped(json, false);
}

export function AnnouncementResponseToJSONTyped(value?: AnnouncementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'effectiveTime': value['effectiveTime'] == null ? undefined : ((value['effectiveTime']).toISOString()),
        'expirationTime': value['expirationTime'] == null ? undefined : ((value['expirationTime']).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

