/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 公告信息
 * @export
 * @interface AnnouncementRequest
 */
export interface AnnouncementRequest {
    /**
     * 公告标题
     * @type {string}
     * @memberof AnnouncementRequest
     */
    title: string;
    /**
     * 公告内容
     * @type {string}
     * @memberof AnnouncementRequest
     */
    content: string;
    /**
     * 生效时间
     * @type {Date}
     * @memberof AnnouncementRequest
     */
    effectiveTime?: Date;
    /**
     * 过期时间
     * @type {Date}
     * @memberof AnnouncementRequest
     */
    expirationTime?: Date;
}

/**
 * Check if a given object implements the AnnouncementRequest interface.
 */
export function instanceOfAnnouncementRequest(value: object): value is AnnouncementRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AnnouncementRequestFromJSON(json: any): AnnouncementRequest {
    return AnnouncementRequestFromJSONTyped(json, false);
}

export function AnnouncementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'effectiveTime': json['effectiveTime'] == null ? undefined : (new Date(json['effectiveTime'])),
        'expirationTime': json['expirationTime'] == null ? undefined : (new Date(json['expirationTime'])),
    };
}

export function AnnouncementRequestToJSON(json: any): AnnouncementRequest {
    return AnnouncementRequestToJSONTyped(json, false);
}

export function AnnouncementRequestToJSONTyped(value?: AnnouncementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'effectiveTime': value['effectiveTime'] == null ? undefined : ((value['effectiveTime']).toISOString()),
        'expirationTime': value['expirationTime'] == null ? undefined : ((value['expirationTime']).toISOString()),
    };
}

