/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiChatStreamV2PostRequest
 */
export interface ApiChatStreamV2PostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiChatStreamV2PostRequest
     */
    key?: string;
}

/**
 * Check if a given object implements the ApiChatStreamV2PostRequest interface.
 */
export function instanceOfApiChatStreamV2PostRequest(value: object): value is ApiChatStreamV2PostRequest {
    return true;
}

export function ApiChatStreamV2PostRequestFromJSON(json: any): ApiChatStreamV2PostRequest {
    return ApiChatStreamV2PostRequestFromJSONTyped(json, false);
}

export function ApiChatStreamV2PostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2PostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function ApiChatStreamV2PostRequestToJSON(json: any): ApiChatStreamV2PostRequest {
    return ApiChatStreamV2PostRequestToJSONTyped(json, false);
}

export function ApiChatStreamV2PostRequestToJSONTyped(value?: ApiChatStreamV2PostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

