/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChatStreamV2Post200ResponseFailure } from './ApiChatStreamV2Post200ResponseFailure';
import {
    ApiChatStreamV2Post200ResponseFailureFromJSON,
    ApiChatStreamV2Post200ResponseFailureFromJSONTyped,
    ApiChatStreamV2Post200ResponseFailureToJSON,
    ApiChatStreamV2Post200ResponseFailureToJSONTyped,
} from './ApiChatStreamV2Post200ResponseFailure';
import type { ApiChatStreamV2Post200ResponseTimeoutCallback } from './ApiChatStreamV2Post200ResponseTimeoutCallback';
import {
    ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSON,
    ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSONTyped,
    ApiChatStreamV2Post200ResponseTimeoutCallbackToJSON,
    ApiChatStreamV2Post200ResponseTimeoutCallbackToJSONTyped,
} from './ApiChatStreamV2Post200ResponseTimeoutCallback';
import type { ApiChatStreamV2Post200ResponseEarlySendAttemptsInner } from './ApiChatStreamV2Post200ResponseEarlySendAttemptsInner';
import {
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSON,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSONTyped,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSON,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSONTyped,
} from './ApiChatStreamV2Post200ResponseEarlySendAttemptsInner';

/**
 * 
 * @export
 * @interface ApiChatStreamV2Post200Response
 */
export interface ApiChatStreamV2Post200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiChatStreamV2Post200Response
     */
    timeout?: number | null;
    /**
     * 
     * @type {object}
     * @memberof ApiChatStreamV2Post200Response
     */
    handler?: object | null;
    /**
     * 
     * @type {Array<ApiChatStreamV2Post200ResponseEarlySendAttemptsInner>}
     * @memberof ApiChatStreamV2Post200Response
     */
    earlySendAttempts?: Array<ApiChatStreamV2Post200ResponseEarlySendAttemptsInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ApiChatStreamV2Post200Response
     */
    complete?: boolean;
    /**
     * 
     * @type {ApiChatStreamV2Post200ResponseFailure}
     * @memberof ApiChatStreamV2Post200Response
     */
    failure?: ApiChatStreamV2Post200ResponseFailure | null;
    /**
     * 
     * @type {ApiChatStreamV2Post200ResponseTimeoutCallback}
     * @memberof ApiChatStreamV2Post200Response
     */
    timeoutCallback?: ApiChatStreamV2Post200ResponseTimeoutCallback;
    /**
     * 
     * @type {object}
     * @memberof ApiChatStreamV2Post200Response
     */
    errorCallback?: object;
    /**
     * 
     * @type {ApiChatStreamV2Post200ResponseTimeoutCallback}
     * @memberof ApiChatStreamV2Post200Response
     */
    completionCallback?: ApiChatStreamV2Post200ResponseTimeoutCallback;
}

/**
 * Check if a given object implements the ApiChatStreamV2Post200Response interface.
 */
export function instanceOfApiChatStreamV2Post200Response(value: object): value is ApiChatStreamV2Post200Response {
    return true;
}

export function ApiChatStreamV2Post200ResponseFromJSON(json: any): ApiChatStreamV2Post200Response {
    return ApiChatStreamV2Post200ResponseFromJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2Post200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'handler': json['handler'] == null ? undefined : json['handler'],
        'earlySendAttempts': json['earlySendAttempts'] == null ? undefined : ((json['earlySendAttempts'] as Array<any>).map(ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSON)),
        'complete': json['complete'] == null ? undefined : json['complete'],
        'failure': json['failure'] == null ? undefined : ApiChatStreamV2Post200ResponseFailureFromJSON(json['failure']),
        'timeoutCallback': json['timeoutCallback'] == null ? undefined : ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSON(json['timeoutCallback']),
        'errorCallback': json['errorCallback'] == null ? undefined : json['errorCallback'],
        'completionCallback': json['completionCallback'] == null ? undefined : ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSON(json['completionCallback']),
    };
}

export function ApiChatStreamV2Post200ResponseToJSON(json: any): ApiChatStreamV2Post200Response {
    return ApiChatStreamV2Post200ResponseToJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseToJSONTyped(value?: ApiChatStreamV2Post200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeout': value['timeout'],
        'handler': value['handler'],
        'earlySendAttempts': value['earlySendAttempts'] == null ? undefined : ((value['earlySendAttempts'] as Array<any>).map(ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSON)),
        'complete': value['complete'],
        'failure': ApiChatStreamV2Post200ResponseFailureToJSON(value['failure']),
        'timeoutCallback': ApiChatStreamV2Post200ResponseTimeoutCallbackToJSON(value['timeoutCallback']),
        'errorCallback': value['errorCallback'],
        'completionCallback': ApiChatStreamV2Post200ResponseTimeoutCallbackToJSON(value['completionCallback']),
    };
}

