/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType } from './ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType';
import {
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSON,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSONTyped,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSON,
    ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSONTyped,
} from './ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType';

/**
 * org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.DataWithMediaType
 * @export
 * @interface ApiChatStreamV2Post200ResponseEarlySendAttemptsInner
 */
export interface ApiChatStreamV2Post200ResponseEarlySendAttemptsInner {
    /**
     * 
     * @type {object}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInner
     */
    data?: object;
    /**
     * 
     * @type {ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInner
     */
    mediaType?: ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType | null;
}

/**
 * Check if a given object implements the ApiChatStreamV2Post200ResponseEarlySendAttemptsInner interface.
 */
export function instanceOfApiChatStreamV2Post200ResponseEarlySendAttemptsInner(value: object): value is ApiChatStreamV2Post200ResponseEarlySendAttemptsInner {
    return true;
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSON(json: any): ApiChatStreamV2Post200ResponseEarlySendAttemptsInner {
    return ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2Post200ResponseEarlySendAttemptsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'mediaType': json['mediaType'] == null ? undefined : ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSON(json['mediaType']),
    };
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSON(json: any): ApiChatStreamV2Post200ResponseEarlySendAttemptsInner {
    return ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerToJSONTyped(value?: ApiChatStreamV2Post200ResponseEarlySendAttemptsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'mediaType': ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSON(value['mediaType']),
    };
}

