/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChatStreamV2Post200ResponseFailureCauseStackTraceInner } from './ApiChatStreamV2Post200ResponseFailureCauseStackTraceInner';
import {
    ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerFromJSON,
    ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerFromJSONTyped,
    ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerToJSON,
    ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerToJSONTyped,
} from './ApiChatStreamV2Post200ResponseFailureCauseStackTraceInner';
import type { ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInner } from './ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInner';
import {
    ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerFromJSON,
    ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerFromJSONTyped,
    ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerToJSON,
    ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerToJSONTyped,
} from './ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInner';
import type { ApiChatStreamV2Post200ResponseFailureCause } from './ApiChatStreamV2Post200ResponseFailureCause';
import {
    ApiChatStreamV2Post200ResponseFailureCauseFromJSON,
    ApiChatStreamV2Post200ResponseFailureCauseFromJSONTyped,
    ApiChatStreamV2Post200ResponseFailureCauseToJSON,
    ApiChatStreamV2Post200ResponseFailureCauseToJSONTyped,
} from './ApiChatStreamV2Post200ResponseFailureCause';

/**
 * 
 * @export
 * @interface ApiChatStreamV2Post200ResponseFailure
 */
export interface ApiChatStreamV2Post200ResponseFailure {
    /**
     * Specific details about the Throwable.  For example, for
     * {@code FileNotFoundException}, this contains the name of
     * the file that could not be found.
     * @type {string}
     * @memberof ApiChatStreamV2Post200ResponseFailure
     */
    detailMessage?: string;
    /**
     * 
     * @type {ApiChatStreamV2Post200ResponseFailureCause}
     * @memberof ApiChatStreamV2Post200ResponseFailure
     */
    cause?: ApiChatStreamV2Post200ResponseFailureCause;
    /**
     * The stack trace, as returned by{@link #getStackTrace()}.
     * 
     * The field is initialized to a zero-length array.  A{@code
     *     * null} value of this field indicates subsequent calls to{@link
     *     * #setStackTrace(StackTraceElement[])} and{@link
     *     * #fillInStackTrace()} will be no-ops.
     * @type {Array<ApiChatStreamV2Post200ResponseFailureCauseStackTraceInner>}
     * @memberof ApiChatStreamV2Post200ResponseFailure
     */
    stackTrace?: Array<ApiChatStreamV2Post200ResponseFailureCauseStackTraceInner>;
    /**
     * The list of suppressed exceptions, as returned by{@link
     *     * #getSuppressed()}.  The list is initialized to a zero-element
     * unmodifiable sentinel list.  When a serialized Throwable is
     * read in, if the{@code suppressedExceptions} field points to a
     * zero-element list, the field is reset to the sentinel value.
     * @type {Array<ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInner>}
     * @memberof ApiChatStreamV2Post200ResponseFailure
     */
    suppressedExceptions?: Array<ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInner>;
}

/**
 * Check if a given object implements the ApiChatStreamV2Post200ResponseFailure interface.
 */
export function instanceOfApiChatStreamV2Post200ResponseFailure(value: object): value is ApiChatStreamV2Post200ResponseFailure {
    return true;
}

export function ApiChatStreamV2Post200ResponseFailureFromJSON(json: any): ApiChatStreamV2Post200ResponseFailure {
    return ApiChatStreamV2Post200ResponseFailureFromJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2Post200ResponseFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'detailMessage': json['detailMessage'] == null ? undefined : json['detailMessage'],
        'cause': json['cause'] == null ? undefined : ApiChatStreamV2Post200ResponseFailureCauseFromJSON(json['cause']),
        'stackTrace': json['stackTrace'] == null ? undefined : ((json['stackTrace'] as Array<any>).map(ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerFromJSON)),
        'suppressedExceptions': json['suppressedExceptions'] == null ? undefined : ((json['suppressedExceptions'] as Array<any>).map(ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerFromJSON)),
    };
}

export function ApiChatStreamV2Post200ResponseFailureToJSON(json: any): ApiChatStreamV2Post200ResponseFailure {
    return ApiChatStreamV2Post200ResponseFailureToJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseFailureToJSONTyped(value?: ApiChatStreamV2Post200ResponseFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detailMessage': value['detailMessage'],
        'cause': ApiChatStreamV2Post200ResponseFailureCauseToJSON(value['cause']),
        'stackTrace': value['stackTrace'] == null ? undefined : ((value['stackTrace'] as Array<any>).map(ApiChatStreamV2Post200ResponseFailureCauseStackTraceInnerToJSON)),
        'suppressedExceptions': value['suppressedExceptions'] == null ? undefined : ((value['suppressedExceptions'] as Array<any>).map(ApiChatStreamV2Post200ResponseFailureSuppressedExceptionsInnerToJSON)),
    };
}

