/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChatStreamV2PostRequest } from './ApiChatStreamV2PostRequest';
import {
    ApiChatStreamV2PostRequestFromJSON,
    ApiChatStreamV2PostRequestFromJSONTyped,
    ApiChatStreamV2PostRequestToJSON,
    ApiChatStreamV2PostRequestToJSONTyped,
} from './ApiChatStreamV2PostRequest';

/**
 * 
 * @export
 * @interface ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType
 */
export interface ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType {
    /**
     * 
     * @type {string}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType
     */
    subtype?: string;
    /**
     * 
     * @type {ApiChatStreamV2PostRequest}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType
     */
    parameters?: ApiChatStreamV2PostRequest;
    /**
     * 
     * @type {string}
     * @memberof ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType
     */
    toStringValue?: string | null;
}

/**
 * Check if a given object implements the ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType interface.
 */
export function instanceOfApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType(value: object): value is ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType {
    return true;
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSON(json: any): ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType {
    return ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
        'parameters': json['parameters'] == null ? undefined : ApiChatStreamV2PostRequestFromJSON(json['parameters']),
        'toStringValue': json['toStringValue'] == null ? undefined : json['toStringValue'],
    };
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSON(json: any): ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType {
    return ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaTypeToJSONTyped(value?: ApiChatStreamV2Post200ResponseEarlySendAttemptsInnerMediaType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'subtype': value['subtype'],
        'parameters': ApiChatStreamV2PostRequestToJSON(value['parameters']),
        'toStringValue': value['toStringValue'],
    };
}

