/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiChatStreamV2Post200ResponseTimeoutCallback
 */
export interface ApiChatStreamV2Post200ResponseTimeoutCallback {
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiChatStreamV2Post200ResponseTimeoutCallback
     */
    delegates?: Array<object>;
}

/**
 * Check if a given object implements the ApiChatStreamV2Post200ResponseTimeoutCallback interface.
 */
export function instanceOfApiChatStreamV2Post200ResponseTimeoutCallback(value: object): value is ApiChatStreamV2Post200ResponseTimeoutCallback {
    return true;
}

export function ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSON(json: any): ApiChatStreamV2Post200ResponseTimeoutCallback {
    return ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseTimeoutCallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatStreamV2Post200ResponseTimeoutCallback {
    if (json == null) {
        return json;
    }
    return {
        
        'delegates': json['delegates'] == null ? undefined : json['delegates'],
    };
}

export function ApiChatStreamV2Post200ResponseTimeoutCallbackToJSON(json: any): ApiChatStreamV2Post200ResponseTimeoutCallback {
    return ApiChatStreamV2Post200ResponseTimeoutCallbackToJSONTyped(json, false);
}

export function ApiChatStreamV2Post200ResponseTimeoutCallbackToJSONTyped(value?: ApiChatStreamV2Post200ResponseTimeoutCallback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delegates': value['delegates'],
    };
}

