/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * API密钥配置实体
 * @export
 * @interface ApiKeyConfig
 */
export interface ApiKeyConfig {
    /**
     * 配置ID
     * @type {number}
     * @memberof ApiKeyConfig
     */
    id?: number;
    /**
     * API密钥名称
     * @type {string}
     * @memberof ApiKeyConfig
     */
    name?: string;
    /**
     * Dify API密钥
     * @type {string}
     * @memberof ApiKeyConfig
     */
    apiKey?: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof ApiKeyConfig
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof ApiKeyConfig
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ApiKeyConfig interface.
 */
export function instanceOfApiKeyConfig(value: object): value is ApiKeyConfig {
    return true;
}

export function ApiKeyConfigFromJSON(json: any): ApiKeyConfig {
    return ApiKeyConfigFromJSONTyped(json, false);
}

export function ApiKeyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ApiKeyConfigToJSON(json: any): ApiKeyConfig {
    return ApiKeyConfigToJSONTyped(json, false);
}

export function ApiKeyConfigToJSONTyped(value?: ApiKeyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'apiKey': value['apiKey'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

