/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * API密钥配置信息
 * @export
 * @interface ApiKeyConfigRequest
 */
export interface ApiKeyConfigRequest {
    /**
     * API密钥名称
     * @type {string}
     * @memberof ApiKeyConfigRequest
     */
    name: string;
    /**
     * Dify API密钥
     * @type {string}
     * @memberof ApiKeyConfigRequest
     */
    apiKey: string;
}

/**
 * Check if a given object implements the ApiKeyConfigRequest interface.
 */
export function instanceOfApiKeyConfigRequest(value: object): value is ApiKeyConfigRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function ApiKeyConfigRequestFromJSON(json: any): ApiKeyConfigRequest {
    return ApiKeyConfigRequestFromJSONTyped(json, false);
}

export function ApiKeyConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'apiKey': json['apiKey'],
    };
}

export function ApiKeyConfigRequestToJSON(json: any): ApiKeyConfigRequest {
    return ApiKeyConfigRequestToJSONTyped(json, false);
}

export function ApiKeyConfigRequestToJSONTyped(value?: ApiKeyConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'apiKey': value['apiKey'],
    };
}

