/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Announcement } from './Announcement';
import {
    AnnouncementFromJSON,
    AnnouncementFromJSONTyped,
    AnnouncementToJSON,
    AnnouncementToJSONTyped,
} from './Announcement';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseAnnouncement
 */
export interface ApiResponseAnnouncement {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseAnnouncement
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseAnnouncement
     */
    message?: string;
    /**
     * 
     * @type {Announcement}
     * @memberof ApiResponseAnnouncement
     */
    data?: Announcement;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseAnnouncement
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseAnnouncement interface.
 */
export function instanceOfApiResponseAnnouncement(value: object): value is ApiResponseAnnouncement {
    return true;
}

export function ApiResponseAnnouncementFromJSON(json: any): ApiResponseAnnouncement {
    return ApiResponseAnnouncementFromJSONTyped(json, false);
}

export function ApiResponseAnnouncementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseAnnouncement {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AnnouncementFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseAnnouncementToJSON(json: any): ApiResponseAnnouncement {
    return ApiResponseAnnouncementToJSONTyped(json, false);
}

export function ApiResponseAnnouncementToJSONTyped(value?: ApiResponseAnnouncement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': AnnouncementToJSON(value['data']),
        'column': value['column'],
    };
}

