/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用API响应
 * @export
 * @interface ApiResponseListMapStringObject
 */
export interface ApiResponseListMapStringObject {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseListMapStringObject
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseListMapStringObject
     */
    message?: string;
    /**
     * 响应数据
     * @type {Array<{ [key: string]: string; }>}
     * @memberof ApiResponseListMapStringObject
     */
    data?: Array<{ [key: string]: string; }>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListMapStringObject
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseListMapStringObject interface.
 */
export function instanceOfApiResponseListMapStringObject(value: object): value is ApiResponseListMapStringObject {
    return true;
}

export function ApiResponseListMapStringObjectFromJSON(json: any): ApiResponseListMapStringObject {
    return ApiResponseListMapStringObjectFromJSONTyped(json, false);
}

export function ApiResponseListMapStringObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListMapStringObject {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseListMapStringObjectToJSON(json: any): ApiResponseListMapStringObject {
    return ApiResponseListMapStringObjectToJSONTyped(json, false);
}

export function ApiResponseListMapStringObjectToJSONTyped(value?: ApiResponseListMapStringObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'column': value['column'],
    };
}

