/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupResponse } from './GroupResponse';
import {
    GroupResponseFromJSON,
    GroupResponseFromJSONTyped,
    GroupResponseToJSON,
    GroupResponseToJSONTyped,
} from './GroupResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseGroupResponse
 */
export interface ApiResponseGroupResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseGroupResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseGroupResponse
     */
    message?: string;
    /**
     * 
     * @type {GroupResponse}
     * @memberof ApiResponseGroupResponse
     */
    data?: GroupResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseGroupResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseGroupResponse interface.
 */
export function instanceOfApiResponseGroupResponse(value: object): value is ApiResponseGroupResponse {
    return true;
}

export function ApiResponseGroupResponseFromJSON(json: any): ApiResponseGroupResponse {
    return ApiResponseGroupResponseFromJSONTyped(json, false);
}

export function ApiResponseGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : GroupResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseGroupResponseToJSON(json: any): ApiResponseGroupResponse {
    return ApiResponseGroupResponseToJSONTyped(json, false);
}

export function ApiResponseGroupResponseToJSONTyped(value?: ApiResponseGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': GroupResponseToJSON(value['data']),
        'column': value['column'],
    };
}

