/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseGroupResponse } from './PageResponseGroupResponse';
import {
    PageResponseGroupResponseFromJSON,
    PageResponseGroupResponseFromJSONTyped,
    PageResponseGroupResponseToJSON,
    PageResponseGroupResponseToJSONTyped,
} from './PageResponseGroupResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseGroupResponse
 */
export interface ApiResponsePageResponseGroupResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseGroupResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseGroupResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseGroupResponse}
     * @memberof ApiResponsePageResponseGroupResponse
     */
    data?: PageResponseGroupResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseGroupResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseGroupResponse interface.
 */
export function instanceOfApiResponsePageResponseGroupResponse(value: object): value is ApiResponsePageResponseGroupResponse {
    return true;
}

export function ApiResponsePageResponseGroupResponseFromJSON(json: any): ApiResponsePageResponseGroupResponse {
    return ApiResponsePageResponseGroupResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseGroupResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseGroupResponseToJSON(json: any): ApiResponsePageResponseGroupResponse {
    return ApiResponsePageResponseGroupResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseGroupResponseToJSONTyped(value?: ApiResponsePageResponseGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseGroupResponseToJSON(value['data']),
        'column': value['column'],
    };
}

