/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Conversation } from './Conversation';
import {
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
    ConversationToJSONTyped,
} from './Conversation';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseConversation
 */
export interface ApiResponseConversation {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseConversation
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseConversation
     */
    message?: string;
    /**
     * 
     * @type {Conversation}
     * @memberof ApiResponseConversation
     */
    data?: Conversation;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseConversation
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseConversation interface.
 */
export function instanceOfApiResponseConversation(value: object): value is ApiResponseConversation {
    return true;
}

export function ApiResponseConversationFromJSON(json: any): ApiResponseConversation {
    return ApiResponseConversationFromJSONTyped(json, false);
}

export function ApiResponseConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseConversation {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ConversationFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseConversationToJSON(json: any): ApiResponseConversation {
    return ApiResponseConversationToJSONTyped(json, false);
}

export function ApiResponseConversationToJSONTyped(value?: ApiResponseConversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ConversationToJSON(value['data']),
        'column': value['column'],
    };
}

