/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseApiKeyConfig } from './PageResponseApiKeyConfig';
import {
    PageResponseApiKeyConfigFromJSON,
    PageResponseApiKeyConfigFromJSONTyped,
    PageResponseApiKeyConfigToJSON,
    PageResponseApiKeyConfigToJSONTyped,
} from './PageResponseApiKeyConfig';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseApiKeyConfig
 */
export interface ApiResponsePageResponseApiKeyConfig {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseApiKeyConfig
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseApiKeyConfig
     */
    message?: string;
    /**
     * 
     * @type {PageResponseApiKeyConfig}
     * @memberof ApiResponsePageResponseApiKeyConfig
     */
    data?: PageResponseApiKeyConfig;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseApiKeyConfig
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseApiKeyConfig interface.
 */
export function instanceOfApiResponsePageResponseApiKeyConfig(value: object): value is ApiResponsePageResponseApiKeyConfig {
    return true;
}

export function ApiResponsePageResponseApiKeyConfigFromJSON(json: any): ApiResponsePageResponseApiKeyConfig {
    return ApiResponsePageResponseApiKeyConfigFromJSONTyped(json, false);
}

export function ApiResponsePageResponseApiKeyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseApiKeyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseApiKeyConfigFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseApiKeyConfigToJSON(json: any): ApiResponsePageResponseApiKeyConfig {
    return ApiResponsePageResponseApiKeyConfigToJSONTyped(json, false);
}

export function ApiResponsePageResponseApiKeyConfigToJSONTyped(value?: ApiResponsePageResponseApiKeyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseApiKeyConfigToJSON(value['data']),
        'column': value['column'],
    };
}

