/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseUserInfoResponse } from './PageResponseUserInfoResponse';
import {
    PageResponseUserInfoResponseFromJSON,
    PageResponseUserInfoResponseFromJSONTyped,
    PageResponseUserInfoResponseToJSON,
    PageResponseUserInfoResponseToJSONTyped,
} from './PageResponseUserInfoResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseUserInfoResponse
 */
export interface ApiResponsePageResponseUserInfoResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseUserInfoResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseUserInfoResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseUserInfoResponse}
     * @memberof ApiResponsePageResponseUserInfoResponse
     */
    data?: PageResponseUserInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseUserInfoResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseUserInfoResponse interface.
 */
export function instanceOfApiResponsePageResponseUserInfoResponse(value: object): value is ApiResponsePageResponseUserInfoResponse {
    return true;
}

export function ApiResponsePageResponseUserInfoResponseFromJSON(json: any): ApiResponsePageResponseUserInfoResponse {
    return ApiResponsePageResponseUserInfoResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseUserInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseUserInfoResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseUserInfoResponseToJSON(json: any): ApiResponsePageResponseUserInfoResponse {
    return ApiResponsePageResponseUserInfoResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseUserInfoResponseToJSONTyped(value?: ApiResponsePageResponseUserInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseUserInfoResponseToJSON(value['data']),
        'column': value['column'],
    };
}

