/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseConversationResponse } from './PageResponseConversationResponse';
import {
    PageResponseConversationResponseFromJSON,
    PageResponseConversationResponseFromJSONTyped,
    PageResponseConversationResponseToJSON,
    PageResponseConversationResponseToJSONTyped,
} from './PageResponseConversationResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseConversationResponse
 */
export interface ApiResponsePageResponseConversationResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseConversationResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseConversationResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseConversationResponse}
     * @memberof ApiResponsePageResponseConversationResponse
     */
    data?: PageResponseConversationResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseConversationResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseConversationResponse interface.
 */
export function instanceOfApiResponsePageResponseConversationResponse(value: object): value is ApiResponsePageResponseConversationResponse {
    return true;
}

export function ApiResponsePageResponseConversationResponseFromJSON(json: any): ApiResponsePageResponseConversationResponse {
    return ApiResponsePageResponseConversationResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseConversationResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseConversationResponseToJSON(json: any): ApiResponsePageResponseConversationResponse {
    return ApiResponsePageResponseConversationResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseConversationResponseToJSONTyped(value?: ApiResponsePageResponseConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseConversationResponseToJSON(value['data']),
        'column': value['column'],
    };
}

