/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnnouncementResponse } from './AnnouncementResponse';
import {
    AnnouncementResponseFromJSON,
    AnnouncementResponseFromJSONTyped,
    AnnouncementResponseToJSON,
    AnnouncementResponseToJSONTyped,
} from './AnnouncementResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseListAnnouncementResponse
 */
export interface ApiResponseListAnnouncementResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseListAnnouncementResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseListAnnouncementResponse
     */
    message?: string;
    /**
     * 响应数据
     * @type {Array<AnnouncementResponse>}
     * @memberof ApiResponseListAnnouncementResponse
     */
    data?: Array<AnnouncementResponse>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListAnnouncementResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseListAnnouncementResponse interface.
 */
export function instanceOfApiResponseListAnnouncementResponse(value: object): value is ApiResponseListAnnouncementResponse {
    return true;
}

export function ApiResponseListAnnouncementResponseFromJSON(json: any): ApiResponseListAnnouncementResponse {
    return ApiResponseListAnnouncementResponseFromJSONTyped(json, false);
}

export function ApiResponseListAnnouncementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListAnnouncementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AnnouncementResponseFromJSON)),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseListAnnouncementResponseToJSON(json: any): ApiResponseListAnnouncementResponse {
    return ApiResponseListAnnouncementResponseToJSONTyped(json, false);
}

export function ApiResponseListAnnouncementResponseToJSONTyped(value?: ApiResponseListAnnouncementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AnnouncementResponseToJSON)),
        'column': value['column'],
    };
}

