/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponsePermissionResponse } from './PageResponsePermissionResponse';
import {
    PageResponsePermissionResponseFromJSON,
    PageResponsePermissionResponseFromJSONTyped,
    PageResponsePermissionResponseToJSON,
    PageResponsePermissionResponseToJSONTyped,
} from './PageResponsePermissionResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponsePermissionResponse
 */
export interface ApiResponsePageResponsePermissionResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponsePermissionResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponsePermissionResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponsePermissionResponse}
     * @memberof ApiResponsePageResponsePermissionResponse
     */
    data?: PageResponsePermissionResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponsePermissionResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponsePermissionResponse interface.
 */
export function instanceOfApiResponsePageResponsePermissionResponse(value: object): value is ApiResponsePageResponsePermissionResponse {
    return true;
}

export function ApiResponsePageResponsePermissionResponseFromJSON(json: any): ApiResponsePageResponsePermissionResponse {
    return ApiResponsePageResponsePermissionResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponsePermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponsePermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponsePermissionResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponsePermissionResponseToJSON(json: any): ApiResponsePageResponsePermissionResponse {
    return ApiResponsePageResponsePermissionResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponsePermissionResponseToJSONTyped(value?: ApiResponsePageResponsePermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponsePermissionResponseToJSON(value['data']),
        'column': value['column'],
    };
}

