/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyConfig } from './ApiKeyConfig';
import {
    ApiKeyConfigFromJSON,
    ApiKeyConfigFromJSONTyped,
    ApiKeyConfigToJSON,
    ApiKeyConfigToJSONTyped,
} from './ApiKeyConfig';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseApiKeyConfig
 */
export interface ApiResponseApiKeyConfig {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseApiKeyConfig
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseApiKeyConfig
     */
    message?: string;
    /**
     * 
     * @type {ApiKeyConfig}
     * @memberof ApiResponseApiKeyConfig
     */
    data?: ApiKeyConfig;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseApiKeyConfig
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseApiKeyConfig interface.
 */
export function instanceOfApiResponseApiKeyConfig(value: object): value is ApiResponseApiKeyConfig {
    return true;
}

export function ApiResponseApiKeyConfigFromJSON(json: any): ApiResponseApiKeyConfig {
    return ApiResponseApiKeyConfigFromJSONTyped(json, false);
}

export function ApiResponseApiKeyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseApiKeyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ApiKeyConfigFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseApiKeyConfigToJSON(json: any): ApiResponseApiKeyConfig {
    return ApiResponseApiKeyConfigToJSONTyped(json, false);
}

export function ApiResponseApiKeyConfigToJSONTyped(value?: ApiResponseApiKeyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ApiKeyConfigToJSON(value['data']),
        'column': value['column'],
    };
}

