/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleResponse } from './RoleResponse';
import {
    RoleResponseFromJSON,
    RoleResponseFromJSONTyped,
    RoleResponseToJSON,
    RoleResponseToJSONTyped,
} from './RoleResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseRoleResponse
 */
export interface ApiResponseRoleResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseRoleResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseRoleResponse
     */
    message?: string;
    /**
     * 
     * @type {RoleResponse}
     * @memberof ApiResponseRoleResponse
     */
    data?: RoleResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRoleResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseRoleResponse interface.
 */
export function instanceOfApiResponseRoleResponse(value: object): value is ApiResponseRoleResponse {
    return true;
}

export function ApiResponseRoleResponseFromJSON(json: any): ApiResponseRoleResponse {
    return ApiResponseRoleResponseFromJSONTyped(json, false);
}

export function ApiResponseRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : RoleResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseRoleResponseToJSON(json: any): ApiResponseRoleResponse {
    return ApiResponseRoleResponseToJSONTyped(json, false);
}

export function ApiResponseRoleResponseToJSONTyped(value?: ApiResponseRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': RoleResponseToJSON(value['data']),
        'column': value['column'],
    };
}

