/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseWithCursorConversationResponse } from './PageResponseWithCursorConversationResponse';
import {
    PageResponseWithCursorConversationResponseFromJSON,
    PageResponseWithCursorConversationResponseFromJSONTyped,
    PageResponseWithCursorConversationResponseToJSON,
    PageResponseWithCursorConversationResponseToJSONTyped,
} from './PageResponseWithCursorConversationResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseWithCursorConversationResponse
 */
export interface ApiResponsePageResponseWithCursorConversationResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseWithCursorConversationResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseWithCursorConversationResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseWithCursorConversationResponse}
     * @memberof ApiResponsePageResponseWithCursorConversationResponse
     */
    data?: PageResponseWithCursorConversationResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseWithCursorConversationResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseWithCursorConversationResponse interface.
 */
export function instanceOfApiResponsePageResponseWithCursorConversationResponse(value: object): value is ApiResponsePageResponseWithCursorConversationResponse {
    return true;
}

export function ApiResponsePageResponseWithCursorConversationResponseFromJSON(json: any): ApiResponsePageResponseWithCursorConversationResponse {
    return ApiResponsePageResponseWithCursorConversationResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseWithCursorConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseWithCursorConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseWithCursorConversationResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseWithCursorConversationResponseToJSON(json: any): ApiResponsePageResponseWithCursorConversationResponse {
    return ApiResponsePageResponseWithCursorConversationResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseWithCursorConversationResponseToJSONTyped(value?: ApiResponsePageResponseWithCursorConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseWithCursorConversationResponseToJSON(value['data']),
        'column': value['column'],
    };
}

