/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RemainChatInfoResponse } from './RemainChatInfoResponse';
import {
    RemainChatInfoResponseFromJSON,
    RemainChatInfoResponseFromJSONTyped,
    RemainChatInfoResponseToJSON,
    RemainChatInfoResponseToJSONTyped,
} from './RemainChatInfoResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseRemainChatInfoResponse
 */
export interface ApiResponseRemainChatInfoResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseRemainChatInfoResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseRemainChatInfoResponse
     */
    message?: string;
    /**
     * 
     * @type {RemainChatInfoResponse}
     * @memberof ApiResponseRemainChatInfoResponse
     */
    data?: RemainChatInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRemainChatInfoResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseRemainChatInfoResponse interface.
 */
export function instanceOfApiResponseRemainChatInfoResponse(value: object): value is ApiResponseRemainChatInfoResponse {
    return true;
}

export function ApiResponseRemainChatInfoResponseFromJSON(json: any): ApiResponseRemainChatInfoResponse {
    return ApiResponseRemainChatInfoResponseFromJSONTyped(json, false);
}

export function ApiResponseRemainChatInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseRemainChatInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : RemainChatInfoResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseRemainChatInfoResponseToJSON(json: any): ApiResponseRemainChatInfoResponse {
    return ApiResponseRemainChatInfoResponseToJSONTyped(json, false);
}

export function ApiResponseRemainChatInfoResponseToJSONTyped(value?: ApiResponseRemainChatInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': RemainChatInfoResponseToJSON(value['data']),
        'column': value['column'],
    };
}

