/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用API响应
 * @export
 * @interface ApiResponseInteger
 */
export interface ApiResponseInteger {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseInteger
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseInteger
     */
    message?: string;
    /**
     * 响应数据
     * @type {number}
     * @memberof ApiResponseInteger
     */
    data?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseInteger
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseInteger interface.
 */
export function instanceOfApiResponseInteger(value: object): value is ApiResponseInteger {
    return true;
}

export function ApiResponseIntegerFromJSON(json: any): ApiResponseInteger {
    return ApiResponseIntegerFromJSONTyped(json, false);
}

export function ApiResponseIntegerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseInteger {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseIntegerToJSON(json: any): ApiResponseInteger {
    return ApiResponseIntegerToJSONTyped(json, false);
}

export function ApiResponseIntegerToJSONTyped(value?: ApiResponseInteger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'column': value['column'],
    };
}

