/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tips } from './Tips';
import {
    TipsFromJSON,
    TipsFromJSONTyped,
    TipsToJSON,
    TipsToJSONTyped,
} from './Tips';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseTips
 */
export interface ApiResponseTips {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseTips
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseTips
     */
    message?: string;
    /**
     * 
     * @type {Tips}
     * @memberof ApiResponseTips
     */
    data?: Tips;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseTips
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseTips interface.
 */
export function instanceOfApiResponseTips(value: object): value is ApiResponseTips {
    return true;
}

export function ApiResponseTipsFromJSON(json: any): ApiResponseTips {
    return ApiResponseTipsFromJSONTyped(json, false);
}

export function ApiResponseTipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseTips {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : TipsFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseTipsToJSON(json: any): ApiResponseTips {
    return ApiResponseTipsToJSONTyped(json, false);
}

export function ApiResponseTipsToJSONTyped(value?: ApiResponseTips | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': TipsToJSON(value['data']),
        'column': value['column'],
    };
}

