/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用API响应
 * @export
 * @interface ApiResponseObject
 */
export interface ApiResponseObject {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseObject
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseObject
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseObject
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseObject
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseObject interface.
 */
export function instanceOfApiResponseObject(value: object): value is ApiResponseObject {
    return true;
}

export function ApiResponseObjectFromJSON(json: any): ApiResponseObject {
    return ApiResponseObjectFromJSONTyped(json, false);
}

export function ApiResponseObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseObject {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseObjectToJSON(json: any): ApiResponseObject {
    return ApiResponseObjectToJSONTyped(json, false);
}

export function ApiResponseObjectToJSONTyped(value?: ApiResponseObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'column': value['column'],
    };
}

