/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionResponse } from './PermissionResponse';
import {
    PermissionResponseFromJSON,
    PermissionResponseFromJSONTyped,
    PermissionResponseToJSON,
    PermissionResponseToJSONTyped,
} from './PermissionResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePermissionResponse
 */
export interface ApiResponsePermissionResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePermissionResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePermissionResponse
     */
    message?: string;
    /**
     * 
     * @type {PermissionResponse}
     * @memberof ApiResponsePermissionResponse
     */
    data?: PermissionResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePermissionResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePermissionResponse interface.
 */
export function instanceOfApiResponsePermissionResponse(value: object): value is ApiResponsePermissionResponse {
    return true;
}

export function ApiResponsePermissionResponseFromJSON(json: any): ApiResponsePermissionResponse {
    return ApiResponsePermissionResponseFromJSONTyped(json, false);
}

export function ApiResponsePermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PermissionResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePermissionResponseToJSON(json: any): ApiResponsePermissionResponse {
    return ApiResponsePermissionResponseToJSONTyped(json, false);
}

export function ApiResponsePermissionResponseToJSONTyped(value?: ApiResponsePermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PermissionResponseToJSON(value['data']),
        'column': value['column'],
    };
}

