/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionResponse } from './PermissionResponse';
import {
    PermissionResponseFromJSON,
    PermissionResponseFromJSONTyped,
    PermissionResponseToJSON,
    PermissionResponseToJSONTyped,
} from './PermissionResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponseSetPermissionResponse
 */
export interface ApiResponseSetPermissionResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponseSetPermissionResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponseSetPermissionResponse
     */
    message?: string;
    /**
     * 响应数据
     * @type {Set<PermissionResponse>}
     * @memberof ApiResponseSetPermissionResponse
     */
    data?: Set<PermissionResponse>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSetPermissionResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponseSetPermissionResponse interface.
 */
export function instanceOfApiResponseSetPermissionResponse(value: object): value is ApiResponseSetPermissionResponse {
    return true;
}

export function ApiResponseSetPermissionResponseFromJSON(json: any): ApiResponseSetPermissionResponse {
    return ApiResponseSetPermissionResponseFromJSONTyped(json, false);
}

export function ApiResponseSetPermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseSetPermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : (new Set((json['data'] as Array<any>).map(PermissionResponseFromJSON))),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponseSetPermissionResponseToJSON(json: any): ApiResponseSetPermissionResponse {
    return ApiResponseSetPermissionResponseToJSONTyped(json, false);
}

export function ApiResponseSetPermissionResponseToJSONTyped(value?: ApiResponseSetPermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : (Array.from(value['data'] as Set<any>).map(PermissionResponseToJSON)),
        'column': value['column'],
    };
}

