/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseTipsResponse } from './PageResponseTipsResponse';
import {
    PageResponseTipsResponseFromJSON,
    PageResponseTipsResponseFromJSONTyped,
    PageResponseTipsResponseToJSON,
    PageResponseTipsResponseToJSONTyped,
} from './PageResponseTipsResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseTipsResponse
 */
export interface ApiResponsePageResponseTipsResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseTipsResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseTipsResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseTipsResponse}
     * @memberof ApiResponsePageResponseTipsResponse
     */
    data?: PageResponseTipsResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseTipsResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseTipsResponse interface.
 */
export function instanceOfApiResponsePageResponseTipsResponse(value: object): value is ApiResponsePageResponseTipsResponse {
    return true;
}

export function ApiResponsePageResponseTipsResponseFromJSON(json: any): ApiResponsePageResponseTipsResponse {
    return ApiResponsePageResponseTipsResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseTipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseTipsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseTipsResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseTipsResponseToJSON(json: any): ApiResponsePageResponseTipsResponse {
    return ApiResponsePageResponseTipsResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseTipsResponseToJSONTyped(value?: ApiResponsePageResponseTipsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseTipsResponseToJSON(value['data']),
        'column': value['column'],
    };
}

