/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseAnnouncementResponse } from './PageResponseAnnouncementResponse';
import {
    PageResponseAnnouncementResponseFromJSON,
    PageResponseAnnouncementResponseFromJSONTyped,
    PageResponseAnnouncementResponseToJSON,
    PageResponseAnnouncementResponseToJSONTyped,
} from './PageResponseAnnouncementResponse';

/**
 * 通用API响应
 * @export
 * @interface ApiResponsePageResponseAnnouncementResponse
 */
export interface ApiResponsePageResponseAnnouncementResponse {
    /**
     * 响应状态码
     * @type {number}
     * @memberof ApiResponsePageResponseAnnouncementResponse
     */
    code?: number;
    /**
     * 响应消息
     * @type {string}
     * @memberof ApiResponsePageResponseAnnouncementResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseAnnouncementResponse}
     * @memberof ApiResponsePageResponseAnnouncementResponse
     */
    data?: PageResponseAnnouncementResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseAnnouncementResponse
     */
    column?: string;
}

/**
 * Check if a given object implements the ApiResponsePageResponseAnnouncementResponse interface.
 */
export function instanceOfApiResponsePageResponseAnnouncementResponse(value: object): value is ApiResponsePageResponseAnnouncementResponse {
    return true;
}

export function ApiResponsePageResponseAnnouncementResponseFromJSON(json: any): ApiResponsePageResponseAnnouncementResponse {
    return ApiResponsePageResponseAnnouncementResponseFromJSONTyped(json, false);
}

export function ApiResponsePageResponseAnnouncementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageResponseAnnouncementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseAnnouncementResponseFromJSON(json['data']),
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ApiResponsePageResponseAnnouncementResponseToJSON(json: any): ApiResponsePageResponseAnnouncementResponse {
    return ApiResponsePageResponseAnnouncementResponseToJSONTyped(json, false);
}

export function ApiResponsePageResponseAnnouncementResponseToJSONTyped(value?: ApiResponsePageResponseAnnouncementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseAnnouncementResponseToJSON(value['data']),
        'column': value['column'],
    };
}

