/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 对话响应
 * @export
 * @interface ConversationResponse
 */
export interface ConversationResponse {
    /**
     * 对话ID
     * @type {number}
     * @memberof ConversationResponse
     */
    id?: number;
    /**
     * 对话标题
     * @type {string}
     * @memberof ConversationResponse
     */
    title?: string;
    /**
     * 用户ID
     * @type {number}
     * @memberof ConversationResponse
     */
    userId?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof ConversationResponse
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof ConversationResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ConversationResponse interface.
 */
export function instanceOfConversationResponse(value: object): value is ConversationResponse {
    return true;
}

export function ConversationResponseFromJSON(json: any): ConversationResponse {
    return ConversationResponseFromJSONTyped(json, false);
}

export function ConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ConversationResponseToJSON(json: any): ConversationResponse {
    return ConversationResponseToJSONTyped(json, false);
}

export function ConversationResponseToJSONTyped(value?: ConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'userId': value['userId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

