/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 对话实体
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     * 对话ID
     * @type {number}
     * @memberof Conversation
     */
    id?: number;
    /**
     * 对话标识符
     * @type {string}
     * @memberof Conversation
     */
    conversationId?: string;
    /**
     * 用户ID
     * @type {number}
     * @memberof Conversation
     */
    userId?: number;
    /**
     * 对话标题
     * @type {string}
     * @memberof Conversation
     */
    title?: string;
    /**
     * 对话上下文内容（JSON格式）
     * @type {string}
     * @memberof Conversation
     */
    context?: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof Conversation
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof Conversation
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Conversation interface.
 */
export function instanceOfConversation(value: object): value is Conversation {
    return true;
}

export function ConversationFromJSON(json: any): Conversation {
    return ConversationFromJSONTyped(json, false);
}

export function ConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conversation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'conversationId': json['conversationId'] == null ? undefined : json['conversationId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'title': json['title'] == null ? undefined : json['title'],
        'context': json['context'] == null ? undefined : json['context'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ConversationToJSON(json: any): Conversation {
    return ConversationToJSONTyped(json, false);
}

export function ConversationToJSONTyped(value?: Conversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversationId': value['conversationId'],
        'userId': value['userId'],
        'title': value['title'],
        'context': value['context'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

