/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaType } from './MediaType';
import {
    MediaTypeFromJSON,
    MediaTypeFromJSONTyped,
    MediaTypeToJSON,
    MediaTypeToJSONTyped,
} from './MediaType';

/**
 * 
 * @export
 * @interface DataWithMediaType
 */
export interface DataWithMediaType {
    /**
     * 
     * @type {object}
     * @memberof DataWithMediaType
     */
    data?: object;
    /**
     * 
     * @type {MediaType}
     * @memberof DataWithMediaType
     */
    mediaType?: MediaType | null;
}

/**
 * Check if a given object implements the DataWithMediaType interface.
 */
export function instanceOfDataWithMediaType(value: object): value is DataWithMediaType {
    return true;
}

export function DataWithMediaTypeFromJSON(json: any): DataWithMediaType {
    return DataWithMediaTypeFromJSONTyped(json, false);
}

export function DataWithMediaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataWithMediaType {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'mediaType': json['mediaType'] == null ? undefined : MediaTypeFromJSON(json['mediaType']),
    };
}

export function DataWithMediaTypeToJSON(json: any): DataWithMediaType {
    return DataWithMediaTypeToJSONTyped(json, false);
}

export function DataWithMediaTypeToJSONTyped(value?: DataWithMediaType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'mediaType': MediaTypeToJSON(value['mediaType']),
    };
}

