/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultCallback
 */
export interface DefaultCallback {
    /**
     * 
     * @type {Array<object>}
     * @memberof DefaultCallback
     */
    delegates?: Array<object>;
}

/**
 * Check if a given object implements the DefaultCallback interface.
 */
export function instanceOfDefaultCallback(value: object): value is DefaultCallback {
    return true;
}

export function DefaultCallbackFromJSON(json: any): DefaultCallback {
    return DefaultCallbackFromJSONTyped(json, false);
}

export function DefaultCallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultCallback {
    if (json == null) {
        return json;
    }
    return {
        
        'delegates': json['delegates'] == null ? undefined : json['delegates'],
    };
}

export function DefaultCallbackToJSON(json: any): DefaultCallback {
    return DefaultCallbackToJSONTyped(json, false);
}

export function DefaultCallbackToJSONTyped(value?: DefaultCallback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delegates': value['delegates'],
    };
}

