/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 用户组信息
 * @export
 * @interface GroupRequest
 */
export interface GroupRequest {
    /**
     * 用户组名称
     * @type {string}
     * @memberof GroupRequest
     */
    name: string;
    /**
     * 用户组类型
     * @type {string}
     * @memberof GroupRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the GroupRequest interface.
 */
export function instanceOfGroupRequest(value: object): value is GroupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupRequestFromJSON(json: any): GroupRequest {
    return GroupRequestFromJSONTyped(json, false);
}

export function GroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GroupRequestToJSON(json: any): GroupRequest {
    return GroupRequestToJSONTyped(json, false);
}

export function GroupRequestToJSONTyped(value?: GroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
    };
}

