/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JavaLangThrowableCauseStackTraceInner
 */
export interface JavaLangThrowableCauseStackTraceInner {
    /**
     * The name of the class loader.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    classLoaderName?: string;
    /**
     * The module name.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    moduleName?: string;
    /**
     * The module version.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    moduleVersion?: string;
    /**
     * The declaring class.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    declaringClass?: string;
    /**
     * The method name.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    methodName?: string;
    /**
     * The source file name.
     * @type {string}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    fileName?: string;
    /**
     * The source line number.
     * @type {number}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    lineNumber?: number;
    /**
     * Control to show full or partial module, package, and class names.
     * @type {number}
     * @memberof JavaLangThrowableCauseStackTraceInner
     */
    format?: number;
}

/**
 * Check if a given object implements the JavaLangThrowableCauseStackTraceInner interface.
 */
export function instanceOfJavaLangThrowableCauseStackTraceInner(value: object): value is JavaLangThrowableCauseStackTraceInner {
    return true;
}

export function JavaLangThrowableCauseStackTraceInnerFromJSON(json: any): JavaLangThrowableCauseStackTraceInner {
    return JavaLangThrowableCauseStackTraceInnerFromJSONTyped(json, false);
}

export function JavaLangThrowableCauseStackTraceInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): JavaLangThrowableCauseStackTraceInner {
    if (json == null) {
        return json;
    }
    return {
        
        'classLoaderName': json['classLoaderName'] == null ? undefined : json['classLoaderName'],
        'moduleName': json['moduleName'] == null ? undefined : json['moduleName'],
        'moduleVersion': json['moduleVersion'] == null ? undefined : json['moduleVersion'],
        'declaringClass': json['declaringClass'] == null ? undefined : json['declaringClass'],
        'methodName': json['methodName'] == null ? undefined : json['methodName'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
        'format': json['format'] == null ? undefined : json['format'],
    };
}

export function JavaLangThrowableCauseStackTraceInnerToJSON(json: any): JavaLangThrowableCauseStackTraceInner {
    return JavaLangThrowableCauseStackTraceInnerToJSONTyped(json, false);
}

export function JavaLangThrowableCauseStackTraceInnerToJSONTyped(value?: JavaLangThrowableCauseStackTraceInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classLoaderName': value['classLoaderName'],
        'moduleName': value['moduleName'],
        'moduleVersion': value['moduleVersion'],
        'declaringClass': value['declaringClass'],
        'methodName': value['methodName'],
        'fileName': value['fileName'],
        'lineNumber': value['lineNumber'],
        'format': value['format'],
    };
}

