/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JavaLangThrowableCause } from './JavaLangThrowableCause';
import {
    JavaLangThrowableCauseFromJSON,
    JavaLangThrowableCauseFromJSONTyped,
    JavaLangThrowableCauseToJSON,
    JavaLangThrowableCauseToJSONTyped,
} from './JavaLangThrowableCause';
import type { JavaLangThrowableCauseStackTraceInner } from './JavaLangThrowableCauseStackTraceInner';
import {
    JavaLangThrowableCauseStackTraceInnerFromJSON,
    JavaLangThrowableCauseStackTraceInnerFromJSONTyped,
    JavaLangThrowableCauseStackTraceInnerToJSON,
    JavaLangThrowableCauseStackTraceInnerToJSONTyped,
} from './JavaLangThrowableCauseStackTraceInner';
import type { JavaLangThrowableSuppressedExceptionsInner } from './JavaLangThrowableSuppressedExceptionsInner';
import {
    JavaLangThrowableSuppressedExceptionsInnerFromJSON,
    JavaLangThrowableSuppressedExceptionsInnerFromJSONTyped,
    JavaLangThrowableSuppressedExceptionsInnerToJSON,
    JavaLangThrowableSuppressedExceptionsInnerToJSONTyped,
} from './JavaLangThrowableSuppressedExceptionsInner';

/**
 * 
 * @export
 * @interface JavaLangThrowable
 */
export interface JavaLangThrowable {
    /**
     * Specific details about the Throwable.  For example, for
     * {@code FileNotFoundException}, this contains the name of
     * the file that could not be found.
     * @type {string}
     * @memberof JavaLangThrowable
     */
    detailMessage?: string;
    /**
     * 
     * @type {JavaLangThrowableCause}
     * @memberof JavaLangThrowable
     */
    cause?: JavaLangThrowableCause;
    /**
     * The stack trace, as returned by{@link #getStackTrace()}.
     * 
     * The field is initialized to a zero-length array.  A{@code
     *     * null} value of this field indicates subsequent calls to{@link
     *     * #setStackTrace(StackTraceElement[])} and{@link
     *     * #fillInStackTrace()} will be no-ops.
     * @type {Array<JavaLangThrowableCauseStackTraceInner>}
     * @memberof JavaLangThrowable
     */
    stackTrace?: Array<JavaLangThrowableCauseStackTraceInner>;
    /**
     * The list of suppressed exceptions, as returned by{@link
     *     * #getSuppressed()}.  The list is initialized to a zero-element
     * unmodifiable sentinel list.  When a serialized Throwable is
     * read in, if the{@code suppressedExceptions} field points to a
     * zero-element list, the field is reset to the sentinel value.
     * @type {Array<JavaLangThrowableSuppressedExceptionsInner>}
     * @memberof JavaLangThrowable
     */
    suppressedExceptions?: Array<JavaLangThrowableSuppressedExceptionsInner>;
}

/**
 * Check if a given object implements the JavaLangThrowable interface.
 */
export function instanceOfJavaLangThrowable(value: object): value is JavaLangThrowable {
    return true;
}

export function JavaLangThrowableFromJSON(json: any): JavaLangThrowable {
    return JavaLangThrowableFromJSONTyped(json, false);
}

export function JavaLangThrowableFromJSONTyped(json: any, ignoreDiscriminator: boolean): JavaLangThrowable {
    if (json == null) {
        return json;
    }
    return {
        
        'detailMessage': json['detailMessage'] == null ? undefined : json['detailMessage'],
        'cause': json['cause'] == null ? undefined : JavaLangThrowableCauseFromJSON(json['cause']),
        'stackTrace': json['stackTrace'] == null ? undefined : ((json['stackTrace'] as Array<any>).map(JavaLangThrowableCauseStackTraceInnerFromJSON)),
        'suppressedExceptions': json['suppressedExceptions'] == null ? undefined : ((json['suppressedExceptions'] as Array<any>).map(JavaLangThrowableSuppressedExceptionsInnerFromJSON)),
    };
}

export function JavaLangThrowableToJSON(json: any): JavaLangThrowable {
    return JavaLangThrowableToJSONTyped(json, false);
}

export function JavaLangThrowableToJSONTyped(value?: JavaLangThrowable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detailMessage': value['detailMessage'],
        'cause': JavaLangThrowableCauseToJSON(value['cause']),
        'stackTrace': value['stackTrace'] == null ? undefined : ((value['stackTrace'] as Array<any>).map(JavaLangThrowableCauseStackTraceInnerToJSON)),
        'suppressedExceptions': value['suppressedExceptions'] == null ? undefined : ((value['suppressedExceptions'] as Array<any>).map(JavaLangThrowableSuppressedExceptionsInnerToJSON)),
    };
}

