/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapString
 */
export interface MapString {
    /**
     * 
     * @type {string}
     * @memberof MapString
     */
    key?: string;
}

/**
 * Check if a given object implements the MapString interface.
 */
export function instanceOfMapString(value: object): value is MapString {
    return true;
}

export function MapStringFromJSON(json: any): MapString {
    return MapStringFromJSONTyped(json, false);
}

export function MapStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapString {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function MapStringToJSON(json: any): MapString {
    return MapStringToJSONTyped(json, false);
}

export function MapStringToJSONTyped(value?: MapString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

