/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback
 */
export interface OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback {
    /**
     * 
     * @type {Array<object>}
     * @memberof OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback
     */
    delegates?: Array<object>;
}

/**
 * Check if a given object implements the OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback interface.
 */
export function instanceOfOrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback(value: object): value is OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback {
    return true;
}

export function OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackFromJSON(json: any): OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback {
    return OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackFromJSONTyped(json, false);
}

export function OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback {
    if (json == null) {
        return json;
    }
    return {
        
        'delegates': json['delegates'] == null ? undefined : json['delegates'],
    };
}

export function OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackToJSON(json: any): OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback {
    return OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackToJSONTyped(json, false);
}

export function OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallbackToJSONTyped(value?: OrgSpringframeworkWebServletMvcMethodAnnotationResponseBodyEmitterDefaultCallback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delegates': value['delegates'],
    };
}

