/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TipsResponse } from './TipsResponse';
import {
    TipsResponseFromJSON,
    TipsResponseFromJSONTyped,
    TipsResponseToJSON,
    TipsResponseToJSONTyped,
} from './TipsResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponseTipsResponse
 */
export interface PageResponseTipsResponse {
    /**
     * 分页数据列表
     * @type {Array<TipsResponse>}
     * @memberof PageResponseTipsResponse
     */
    content?: Array<TipsResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseTipsResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseTipsResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseTipsResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseTipsResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseTipsResponse interface.
 */
export function instanceOfPageResponseTipsResponse(value: object): value is PageResponseTipsResponse {
    return true;
}

export function PageResponseTipsResponseFromJSON(json: any): PageResponseTipsResponse {
    return PageResponseTipsResponseFromJSONTyped(json, false);
}

export function PageResponseTipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseTipsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(TipsResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseTipsResponseToJSON(json: any): PageResponseTipsResponse {
    return PageResponseTipsResponseToJSONTyped(json, false);
}

export function PageResponseTipsResponseToJSONTyped(value?: PageResponseTipsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(TipsResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

