/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationResponse } from './ConversationResponse';
import {
    ConversationResponseFromJSON,
    ConversationResponseFromJSONTyped,
    ConversationResponseToJSON,
    ConversationResponseToJSONTyped,
} from './ConversationResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponseConversationResponse
 */
export interface PageResponseConversationResponse {
    /**
     * 分页数据列表
     * @type {Array<ConversationResponse>}
     * @memberof PageResponseConversationResponse
     */
    content?: Array<ConversationResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseConversationResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseConversationResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseConversationResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseConversationResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseConversationResponse interface.
 */
export function instanceOfPageResponseConversationResponse(value: object): value is PageResponseConversationResponse {
    return true;
}

export function PageResponseConversationResponseFromJSON(json: any): PageResponseConversationResponse {
    return PageResponseConversationResponseFromJSONTyped(json, false);
}

export function PageResponseConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ConversationResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseConversationResponseToJSON(json: any): PageResponseConversationResponse {
    return PageResponseConversationResponseToJSONTyped(json, false);
}

export function PageResponseConversationResponseToJSONTyped(value?: PageResponseConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ConversationResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

