/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationResponse } from './ConversationResponse';
import {
    ConversationResponseFromJSON,
    ConversationResponseFromJSONTyped,
    ConversationResponseToJSON,
    ConversationResponseToJSONTyped,
} from './ConversationResponse';

/**
 * 游标分页响应
 * @export
 * @interface PageResponseWithCursorConversationResponse
 */
export interface PageResponseWithCursorConversationResponse {
    /**
     * 分页数据列表
     * @type {Array<ConversationResponse>}
     * @memberof PageResponseWithCursorConversationResponse
     */
    list?: Array<ConversationResponse>;
    /**
     * 下一页游标，用于请求下一页数据
     * @type {number}
     * @memberof PageResponseWithCursorConversationResponse
     */
    nextCursor?: number;
    /**
     * 是否还有更多数据
     * @type {boolean}
     * @memberof PageResponseWithCursorConversationResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the PageResponseWithCursorConversationResponse interface.
 */
export function instanceOfPageResponseWithCursorConversationResponse(value: object): value is PageResponseWithCursorConversationResponse {
    return true;
}

export function PageResponseWithCursorConversationResponseFromJSON(json: any): PageResponseWithCursorConversationResponse {
    return PageResponseWithCursorConversationResponseFromJSONTyped(json, false);
}

export function PageResponseWithCursorConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseWithCursorConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(ConversationResponseFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function PageResponseWithCursorConversationResponseToJSON(json: any): PageResponseWithCursorConversationResponse {
    return PageResponseWithCursorConversationResponseToJSONTyped(json, false);
}

export function PageResponseWithCursorConversationResponseToJSONTyped(value?: PageResponseWithCursorConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(ConversationResponseToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

