/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnnouncementResponse } from './AnnouncementResponse';
import {
    AnnouncementResponseFromJSON,
    AnnouncementResponseFromJSONTyped,
    AnnouncementResponseToJSON,
    AnnouncementResponseToJSONTyped,
} from './AnnouncementResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponseAnnouncementResponse
 */
export interface PageResponseAnnouncementResponse {
    /**
     * 分页数据列表
     * @type {Array<AnnouncementResponse>}
     * @memberof PageResponseAnnouncementResponse
     */
    content?: Array<AnnouncementResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseAnnouncementResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseAnnouncementResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseAnnouncementResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseAnnouncementResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseAnnouncementResponse interface.
 */
export function instanceOfPageResponseAnnouncementResponse(value: object): value is PageResponseAnnouncementResponse {
    return true;
}

export function PageResponseAnnouncementResponseFromJSON(json: any): PageResponseAnnouncementResponse {
    return PageResponseAnnouncementResponseFromJSONTyped(json, false);
}

export function PageResponseAnnouncementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseAnnouncementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AnnouncementResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseAnnouncementResponseToJSON(json: any): PageResponseAnnouncementResponse {
    return PageResponseAnnouncementResponseToJSONTyped(json, false);
}

export function PageResponseAnnouncementResponseToJSONTyped(value?: PageResponseAnnouncementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AnnouncementResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

