/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyConfig } from './ApiKeyConfig';
import {
    ApiKeyConfigFromJSON,
    ApiKeyConfigFromJSONTyped,
    ApiKeyConfigToJSON,
    ApiKeyConfigToJSONTyped,
} from './ApiKeyConfig';

/**
 * 分页响应
 * @export
 * @interface PageResponseApiKeyConfig
 */
export interface PageResponseApiKeyConfig {
    /**
     * 分页数据列表
     * @type {Array<ApiKeyConfig>}
     * @memberof PageResponseApiKeyConfig
     */
    content?: Array<ApiKeyConfig>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseApiKeyConfig
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseApiKeyConfig
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseApiKeyConfig
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseApiKeyConfig
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseApiKeyConfig interface.
 */
export function instanceOfPageResponseApiKeyConfig(value: object): value is PageResponseApiKeyConfig {
    return true;
}

export function PageResponseApiKeyConfigFromJSON(json: any): PageResponseApiKeyConfig {
    return PageResponseApiKeyConfigFromJSONTyped(json, false);
}

export function PageResponseApiKeyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseApiKeyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ApiKeyConfigFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseApiKeyConfigToJSON(json: any): PageResponseApiKeyConfig {
    return PageResponseApiKeyConfigToJSONTyped(json, false);
}

export function PageResponseApiKeyConfigToJSONTyped(value?: PageResponseApiKeyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ApiKeyConfigToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

