/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfoResponse } from './UserInfoResponse';
import {
    UserInfoResponseFromJSON,
    UserInfoResponseFromJSONTyped,
    UserInfoResponseToJSON,
    UserInfoResponseToJSONTyped,
} from './UserInfoResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponseUserInfoResponse
 */
export interface PageResponseUserInfoResponse {
    /**
     * 分页数据列表
     * @type {Array<UserInfoResponse>}
     * @memberof PageResponseUserInfoResponse
     */
    content?: Array<UserInfoResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseUserInfoResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseUserInfoResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseUserInfoResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseUserInfoResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseUserInfoResponse interface.
 */
export function instanceOfPageResponseUserInfoResponse(value: object): value is PageResponseUserInfoResponse {
    return true;
}

export function PageResponseUserInfoResponseFromJSON(json: any): PageResponseUserInfoResponse {
    return PageResponseUserInfoResponseFromJSONTyped(json, false);
}

export function PageResponseUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseUserInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserInfoResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseUserInfoResponseToJSON(json: any): PageResponseUserInfoResponse {
    return PageResponseUserInfoResponseToJSONTyped(json, false);
}

export function PageResponseUserInfoResponseToJSONTyped(value?: PageResponseUserInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserInfoResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

