/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleResponse } from './RoleResponse';
import {
    RoleResponseFromJSON,
    RoleResponseFromJSONTyped,
    RoleResponseToJSON,
    RoleResponseToJSONTyped,
} from './RoleResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponseRoleResponse
 */
export interface PageResponseRoleResponse {
    /**
     * 分页数据列表
     * @type {Array<RoleResponse>}
     * @memberof PageResponseRoleResponse
     */
    content?: Array<RoleResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponseRoleResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponseRoleResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponseRoleResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponseRoleResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseRoleResponse interface.
 */
export function instanceOfPageResponseRoleResponse(value: object): value is PageResponseRoleResponse {
    return true;
}

export function PageResponseRoleResponseFromJSON(json: any): PageResponseRoleResponse {
    return PageResponseRoleResponseFromJSONTyped(json, false);
}

export function PageResponseRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RoleResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseRoleResponseToJSON(json: any): PageResponseRoleResponse {
    return PageResponseRoleResponseToJSONTyped(json, false);
}

export function PageResponseRoleResponseToJSONTyped(value?: PageResponseRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RoleResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

