/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionResponse } from './PermissionResponse';
import {
    PermissionResponseFromJSON,
    PermissionResponseFromJSONTyped,
    PermissionResponseToJSON,
    PermissionResponseToJSONTyped,
} from './PermissionResponse';

/**
 * 分页响应
 * @export
 * @interface PageResponsePermissionResponse
 */
export interface PageResponsePermissionResponse {
    /**
     * 分页数据列表
     * @type {Array<PermissionResponse>}
     * @memberof PageResponsePermissionResponse
     */
    content?: Array<PermissionResponse>;
    /**
     * 当前页码（从0开始）
     * @type {number}
     * @memberof PageResponsePermissionResponse
     */
    page?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof PageResponsePermissionResponse
     */
    pageSize?: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageResponsePermissionResponse
     */
    totalElements?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageResponsePermissionResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponsePermissionResponse interface.
 */
export function instanceOfPageResponsePermissionResponse(value: object): value is PageResponsePermissionResponse {
    return true;
}

export function PageResponsePermissionResponseFromJSON(json: any): PageResponsePermissionResponse {
    return PageResponsePermissionResponseFromJSONTyped(json, false);
}

export function PageResponsePermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponsePermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PermissionResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponsePermissionResponseToJSON(json: any): PageResponsePermissionResponse {
    return PageResponsePermissionResponseToJSONTyped(json, false);
}

export function PageResponsePermissionResponseToJSONTyped(value?: PageResponsePermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PermissionResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

