/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 权限响应
 * @export
 * @interface PermissionResponse
 */
export interface PermissionResponse {
    /**
     * 权限ID
     * @type {number}
     * @memberof PermissionResponse
     */
    id?: number;
    /**
     * 限制次数
     * @type {number}
     * @memberof PermissionResponse
     */
    limitCount?: number;
    /**
     * 速率限制的时间单位
     * @type {string}
     * @memberof PermissionResponse
     */
    timeWindowUnit?: PermissionResponseTimeWindowUnitEnum;
    /**
     * 速率限制的时间系数
     * @type {number}
     * @memberof PermissionResponse
     */
    timeWindow?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof PermissionResponse
     */
    createdAt?: Date;
    /**
     * 修改时间
     * @type {Date}
     * @memberof PermissionResponse
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const PermissionResponseTimeWindowUnitEnum = {
    Minute: 'minute',
    Hour: 'hour',
    Day: 'day'
} as const;
export type PermissionResponseTimeWindowUnitEnum = typeof PermissionResponseTimeWindowUnitEnum[keyof typeof PermissionResponseTimeWindowUnitEnum];


/**
 * Check if a given object implements the PermissionResponse interface.
 */
export function instanceOfPermissionResponse(value: object): value is PermissionResponse {
    return true;
}

export function PermissionResponseFromJSON(json: any): PermissionResponse {
    return PermissionResponseFromJSONTyped(json, false);
}

export function PermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'limitCount': json['limitCount'] == null ? undefined : json['limitCount'],
        'timeWindowUnit': json['timeWindowUnit'] == null ? undefined : json['timeWindowUnit'],
        'timeWindow': json['timeWindow'] == null ? undefined : json['timeWindow'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PermissionResponseToJSON(json: any): PermissionResponse {
    return PermissionResponseToJSONTyped(json, false);
}

export function PermissionResponseToJSONTyped(value?: PermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'limitCount': value['limitCount'],
        'timeWindowUnit': value['timeWindowUnit'],
        'timeWindow': value['timeWindow'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

