/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 密码重置请求参数
 * @export
 * @interface ResetRequest
 */
export interface ResetRequest {
    /**
     * 用户邮箱地址
     * @type {string}
     * @memberof ResetRequest
     */
    email: string;
    /**
     * 新密码
     * @type {string}
     * @memberof ResetRequest
     */
    password: string;
    /**
     * 邮箱验证码
     * @type {string}
     * @memberof ResetRequest
     */
    code: string;
}

/**
 * Check if a given object implements the ResetRequest interface.
 */
export function instanceOfResetRequest(value: object): value is ResetRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResetRequestFromJSON(json: any): ResetRequest {
    return ResetRequestFromJSONTyped(json, false);
}

export function ResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'code': json['code'],
    };
}

export function ResetRequestToJSON(json: any): ResetRequest {
    return ResetRequestToJSONTyped(json, false);
}

export function ResetRequestToJSONTyped(value?: ResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'code': value['code'],
    };
}

