/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseEntityApiResponse
 */
export interface ResponseEntityApiResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponseEntityApiResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseEntityApiResponse
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof ResponseEntityApiResponse
     */
    data?: object;
    /**
     * 
     * @type {object}
     * @memberof ResponseEntityApiResponse
     */
    column?: object;
}

/**
 * Check if a given object implements the ResponseEntityApiResponse interface.
 */
export function instanceOfResponseEntityApiResponse(value: object): value is ResponseEntityApiResponse {
    return true;
}

export function ResponseEntityApiResponseFromJSON(json: any): ResponseEntityApiResponse {
    return ResponseEntityApiResponseFromJSONTyped(json, false);
}

export function ResponseEntityApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseEntityApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'column': json['column'] == null ? undefined : json['column'],
    };
}

export function ResponseEntityApiResponseToJSON(json: any): ResponseEntityApiResponse {
    return ResponseEntityApiResponseToJSONTyped(json, false);
}

export function ResponseEntityApiResponseToJSONTyped(value?: ResponseEntityApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'column': value['column'],
    };
}

