/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 角色信息
 * @export
 * @interface RoleRequest
 */
export interface RoleRequest {
    /**
     * 角色名称
     * @type {string}
     * @memberof RoleRequest
     */
    name: string;
    /**
     * 角色类型
     * @type {number}
     * @memberof RoleRequest
     */
    roleType: RoleRequestRoleTypeEnum;
    /**
     * 角色优先级（数值越小权限越高）
     * @type {number}
     * @memberof RoleRequest
     */
    rank: number;
    /**
     * 是否为新用户默认角色
     * @type {boolean}
     * @memberof RoleRequest
     */
    autoAdd?: boolean;
}


/**
 * @export
 */
export const RoleRequestRoleTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type RoleRequestRoleTypeEnum = typeof RoleRequestRoleTypeEnum[keyof typeof RoleRequestRoleTypeEnum];


/**
 * Check if a given object implements the RoleRequest interface.
 */
export function instanceOfRoleRequest(value: object): value is RoleRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roleType' in value) || value['roleType'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function RoleRequestFromJSON(json: any): RoleRequest {
    return RoleRequestFromJSONTyped(json, false);
}

export function RoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'roleType': json['roleType'],
        'rank': json['rank'],
        'autoAdd': json['autoAdd'] == null ? undefined : json['autoAdd'],
    };
}

export function RoleRequestToJSON(json: any): RoleRequest {
    return RoleRequestToJSONTyped(json, false);
}

export function RoleRequestToJSONTyped(value?: RoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'roleType': value['roleType'],
        'rank': value['rank'],
        'autoAdd': value['autoAdd'],
    };
}

