/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 发送验证码请求参数
 * @export
 * @interface SendCodeRequest
 */
export interface SendCodeRequest {
    /**
     * 接收验证码的邮箱地址
     * @type {string}
     * @memberof SendCodeRequest
     */
    email: string;
}

/**
 * Check if a given object implements the SendCodeRequest interface.
 */
export function instanceOfSendCodeRequest(value: object): value is SendCodeRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function SendCodeRequestFromJSON(json: any): SendCodeRequest {
    return SendCodeRequestFromJSONTyped(json, false);
}

export function SendCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function SendCodeRequestToJSON(json: any): SendCodeRequest {
    return SendCodeRequestToJSONTyped(json, false);
}

export function SendCodeRequestToJSONTyped(value?: SendCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

