/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StackTraceElement } from './StackTraceElement';
import {
    StackTraceElementFromJSON,
    StackTraceElementFromJSONTyped,
    StackTraceElementToJSON,
    StackTraceElementToJSONTyped,
} from './StackTraceElement';

/**
 * 
 * @export
 * @interface Throwable
 */
export interface Throwable {
    /**
     * Specific details about the Throwable.  For example, for
     * {@code FileNotFoundException}, this contains the name of
     * the file that could not be found.
     * @type {string}
     * @memberof Throwable
     */
    detailMessage?: string;
    /**
     * 
     * @type {Throwable}
     * @memberof Throwable
     */
    cause?: Throwable;
    /**
     * The stack trace, as returned by{@link #getStackTrace()}.
     * 
     * The field is initialized to a zero-length array.  A{@code
     *     * null} value of this field indicates subsequent calls to{@link
     *     * #setStackTrace(StackTraceElement[])} and{@link
     *     * #fillInStackTrace()} will be no-ops.
     * @type {Array<StackTraceElement>}
     * @memberof Throwable
     */
    stackTrace?: Array<StackTraceElement>;
    /**
     * The list of suppressed exceptions, as returned by{@link
     *     * #getSuppressed()}.  The list is initialized to a zero-element
     * unmodifiable sentinel list.  When a serialized Throwable is
     * read in, if the{@code suppressedExceptions} field points to a
     * zero-element list, the field is reset to the sentinel value.
     * @type {Array<Throwable>}
     * @memberof Throwable
     */
    suppressedExceptions?: Array<Throwable>;
}

/**
 * Check if a given object implements the Throwable interface.
 */
export function instanceOfThrowable(value: object): value is Throwable {
    return true;
}

export function ThrowableFromJSON(json: any): Throwable {
    return ThrowableFromJSONTyped(json, false);
}

export function ThrowableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Throwable {
    if (json == null) {
        return json;
    }
    return {
        
        'detailMessage': json['detailMessage'] == null ? undefined : json['detailMessage'],
        'cause': json['cause'] == null ? undefined : ThrowableFromJSON(json['cause']),
        'stackTrace': json['stackTrace'] == null ? undefined : ((json['stackTrace'] as Array<any>).map(StackTraceElementFromJSON)),
        'suppressedExceptions': json['suppressedExceptions'] == null ? undefined : ((json['suppressedExceptions'] as Array<any>).map(ThrowableFromJSON)),
    };
}

export function ThrowableToJSON(json: any): Throwable {
    return ThrowableToJSONTyped(json, false);
}

export function ThrowableToJSONTyped(value?: Throwable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detailMessage': value['detailMessage'],
        'cause': ThrowableToJSON(value['cause']),
        'stackTrace': value['stackTrace'] == null ? undefined : ((value['stackTrace'] as Array<any>).map(StackTraceElementToJSON)),
        'suppressedExceptions': value['suppressedExceptions'] == null ? undefined : ((value['suppressedExceptions'] as Array<any>).map(ThrowableToJSON)),
    };
}

