/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tips响应
 * @export
 * @interface TipsResponse
 */
export interface TipsResponse {
    /**
     * Tips ID
     * @type {number}
     * @memberof TipsResponse
     */
    id?: number;
    /**
     * Tips标题
     * @type {string}
     * @memberof TipsResponse
     */
    title?: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof TipsResponse
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof TipsResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TipsResponse interface.
 */
export function instanceOfTipsResponse(value: object): value is TipsResponse {
    return true;
}

export function TipsResponseFromJSON(json: any): TipsResponse {
    return TipsResponseFromJSONTyped(json, false);
}

export function TipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TipsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TipsResponseToJSON(json: any): TipsResponse {
    return TipsResponseToJSONTyped(json, false);
}

export function TipsResponseToJSONTyped(value?: TipsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

