/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tips信息
 * @export
 * @interface TipsRequest
 */
export interface TipsRequest {
    /**
     * Tips标题
     * @type {string}
     * @memberof TipsRequest
     */
    title: string;
    /**
     * Tips内容
     * @type {string}
     * @memberof TipsRequest
     */
    content: string;
}

/**
 * Check if a given object implements the TipsRequest interface.
 */
export function instanceOfTipsRequest(value: object): value is TipsRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function TipsRequestFromJSON(json: any): TipsRequest {
    return TipsRequestFromJSONTyped(json, false);
}

export function TipsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TipsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function TipsRequestToJSON(json: any): TipsRequest {
    return TipsRequestToJSONTyped(json, false);
}

export function TipsRequestToJSONTyped(value?: TipsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

