/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tips实体
 * @export
 * @interface Tips
 */
export interface Tips {
    /**
     * Tips ID
     * @type {number}
     * @memberof Tips
     */
    id?: number;
    /**
     * Tips标题
     * @type {string}
     * @memberof Tips
     */
    title?: string;
    /**
     * Tips内容
     * @type {string}
     * @memberof Tips
     */
    content?: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof Tips
     */
    createdAt?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof Tips
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Tips interface.
 */
export function instanceOfTips(value: object): value is Tips {
    return true;
}

export function TipsFromJSON(json: any): Tips {
    return TipsFromJSONTyped(json, false);
}

export function TipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tips {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TipsToJSON(json: any): Tips {
    return TipsToJSONTyped(json, false);
}

export function TipsToJSONTyped(value?: Tips | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

