/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 用户信息
 * @export
 * @interface UserInfoUpdateRequest
 */
export interface UserInfoUpdateRequest {
    /**
     * 用户昵称
     * @type {string}
     * @memberof UserInfoUpdateRequest
     */
    name?: string;
    /**
     * 用户头像URL
     * @type {string}
     * @memberof UserInfoUpdateRequest
     */
    avatar?: string;
}

/**
 * Check if a given object implements the UserInfoUpdateRequest interface.
 */
export function instanceOfUserInfoUpdateRequest(value: object): value is UserInfoUpdateRequest {
    return true;
}

export function UserInfoUpdateRequestFromJSON(json: any): UserInfoUpdateRequest {
    return UserInfoUpdateRequestFromJSONTyped(json, false);
}

export function UserInfoUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function UserInfoUpdateRequestToJSON(json: any): UserInfoUpdateRequest {
    return UserInfoUpdateRequestToJSONTyped(json, false);
}

export function UserInfoUpdateRequestToJSONTyped(value?: UserInfoUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'avatar': value['avatar'],
    };
}

