/* tslint:disable */
/* eslint-disable */
/**
 * mangochat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseObject,
  ApiResponsePageResponseTipsResponse,
  ApiResponseTips,
  TipsRequest,
} from '../models/index';
import {
    ApiResponseObjectFromJSON,
    ApiResponseObjectToJSON,
    ApiResponsePageResponseTipsResponseFromJSON,
    ApiResponsePageResponseTipsResponseToJSON,
    ApiResponseTipsFromJSON,
    ApiResponseTipsToJSON,
    TipsRequestFromJSON,
    TipsRequestToJSON,
} from '../models/index';

export interface CreateTipsRequest {
    authorization?: string;
    tipsRequest?: TipsRequest;
}

export interface CreateTips0Request {
    authorization?: string;
    tipsRequest?: TipsRequest;
}

export interface DeleteTipsRequest {
    id: number;
    authorization?: string;
}

export interface DeleteTips0Request {
    id: number;
    authorization?: string;
}

export interface GetTipsRequest {
    id: number;
    authorization?: string;
}

export interface GetTipsListRequest {
    page?: number;
    pageSize?: number;
    authorization?: string;
}

export interface GetTipsList0Request {
    page?: number;
    pageSize?: number;
    authorization?: string;
}

export interface GetTips0Request {
    id: number;
    authorization?: string;
}

export interface UpdateTipsRequest {
    id: number;
    authorization?: string;
    tipsRequest?: TipsRequest;
}

export interface UpdateTips0Request {
    id: number;
    authorization?: string;
    tipsRequest?: TipsRequest;
}

/**
 * 
 */
export class TipsApi extends runtime.BaseAPI {

    /**
     * 创建新的Tips
     * 创建Tips
     */
    async createTipsRaw(requestParameters: CreateTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TipsRequestToJSON(requestParameters['tipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 创建新的Tips
     * 创建Tips
     */
    async createTips(requestParameters: CreateTipsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.createTipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 创建新的Tips
     * 创建Tips
     */
    async createTips_1Raw(requestParameters: CreateTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TipsRequestToJSON(requestParameters['tipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 创建新的Tips
     * 创建Tips
     */
    async createTips_1(requestParameters: CreateTips0Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.createTips_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 根据ID删除Tips
     * 删除Tips
     */
    async deleteTipsRaw(requestParameters: DeleteTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTips().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 根据ID删除Tips
     * 删除Tips
     */
    async deleteTips(requestParameters: DeleteTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.deleteTipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 根据ID删除Tips
     * 删除Tips
     */
    async deleteTips_2Raw(requestParameters: DeleteTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTips_2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 根据ID删除Tips
     * 删除Tips
     */
    async deleteTips_2(requestParameters: DeleteTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.deleteTips_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 根据Tips ID查询详细信息
     * 根据ID查询Tips
     */
    async getTipsRaw(requestParameters: GetTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseTips>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTips().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseTipsFromJSON(jsonValue));
    }

    /**
     * 根据Tips ID查询详细信息
     * 根据ID查询Tips
     */
    async getTips(requestParameters: GetTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseTips> {
        const response = await this.getTipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 分页查询Tips列表
     * 查询Tips列表
     */
    async getTipsListRaw(requestParameters: GetTipsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePageResponseTipsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePageResponseTipsResponseFromJSON(jsonValue));
    }

    /**
     * 分页查询Tips列表
     * 查询Tips列表
     */
    async getTipsList(requestParameters: GetTipsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePageResponseTipsResponse> {
        const response = await this.getTipsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 分页查询Tips列表
     * 查询Tips列表
     */
    async getTipsList_3Raw(requestParameters: GetTipsList0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePageResponseTipsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePageResponseTipsResponseFromJSON(jsonValue));
    }

    /**
     * 分页查询Tips列表
     * 查询Tips列表
     */
    async getTipsList_3(requestParameters: GetTipsList0Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePageResponseTipsResponse> {
        const response = await this.getTipsList_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 根据Tips ID查询详细信息
     * 根据ID查询Tips
     */
    async getTips_4Raw(requestParameters: GetTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseTips>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTips_4().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseTipsFromJSON(jsonValue));
    }

    /**
     * 根据Tips ID查询详细信息
     * 根据ID查询Tips
     */
    async getTips_4(requestParameters: GetTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseTips> {
        const response = await this.getTips_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新Tips信息
     * 更新Tips
     */
    async updateTipsRaw(requestParameters: UpdateTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTips().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TipsRequestToJSON(requestParameters['tipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 更新Tips信息
     * 更新Tips
     */
    async updateTips(requestParameters: UpdateTipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.updateTipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新Tips信息
     * 更新Tips
     */
    async updateTips_5Raw(requestParameters: UpdateTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTips_5().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/admin/tips`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TipsRequestToJSON(requestParameters['tipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseObjectFromJSON(jsonValue));
    }

    /**
     * 更新Tips信息
     * 更新Tips
     */
    async updateTips_5(requestParameters: UpdateTips0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.updateTips_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
